name: sitemarker
version: 1.0.0
summary: Open source bookmark manager.
description: |
  Make sharing bookmarks easier using Osmata, the bookmark manager.
confinement: strict

base: core22
parts:
  osmata:
    plugin: dump
    source: https://github.com/aerocyber/sitemarker/sitemarker-build-linux.tar.gz

apps:
  osmata:
    command: sitemarker
