name: Build Flatpak

on:
  workflow_dispatch:
  pull_request:

env:
  project-id: io.github.aerocyber.sitemarker

jobs:
  build-flutter-app:
    name: Build and compressed Flutter app
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Build Flutter linux version
        working-directory: ${{ github.workspace }}
        run: |
          ./build-flutter.sh

      - name: Upload app archive to workflow
        uses: actions/upload-artifact@v3
        with:
          name: Sitemarker-Linux
          path: Sitemarker-linux-portable.tar.gz

  build-flatpak:
    name: Build flatpak
    needs: build-flutter-app
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build .flatpak
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v5
        with:
          bundle: Sitemarker.flatpak
          manifest-path: io.github.aerocyber.sitemarker.yml

      - name: Upload .flatpak artifact to workflow
        uses: actions/upload-artifact@v3
        with:
          name: Flatpak artifact
          path: Sitemarker.flatpak